<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class Player extends Model
{
    use HasFactory;

    protected $fillable = ['uuid', 'team_id', 'full_name', 'status', "position"];

    protected static function boot()
    {
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
            $model->status = "Y";
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function team()
    {
        $this->belongsTo(Team::class);
    }
}
