<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;

class SeasonSchedule extends Model
{
    use HasFactory;


    protected $fillable = ["uuid", "season_id", "home_team_id", "away_team_id", "date_scheduled", "match_status"];

    protected static function boot()
    {
        self::creating(function ($model) {
            $model->uuid = str_replace("-", "", Uuid::uuid4());
            $model->match_status = "PENDING";
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public static function generateSchedule($season_id, $home_team, $away_team, $date_scheduled)
    {
        self::create(["season_id" => $season_id, "home_team_id" => $home_team,
            "away_team_id" => $away_team, "date_scheduled" => date("Y-m-d",strtotime($date_scheduled))]);
    }
}
