<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;
use DB;

class SeasonTeamPlayers extends Model
{
    use HasFactory;
    protected $fillable = ["season_id", "team_id", "player_id", "uuid"];

    public static function createSeasonPlayers($id)
    {
        $teams=DB::table("teams as t")
            ->join("players as p","p.team_id","=","t.id")
            ->select("p.id","p.team_id")->get();
        for ($i=0;$i<count($teams);$i++){
            SeasonTeamPlayers::create(["season_id" => $id,
                "team_id" => $teams[$i]->team_id, "player_id" => $teams[$i]->id]);
        }

    }

    protected static function boot()
    {
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }


}
