<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;
use Ramsey\Uuid\Uuid;

class Season extends Model
{
    use HasFactory;

    protected $fillable = ["uuid", "season_name", "created_by", "season_status"];

    protected static function boot()
    {
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public static function createSeason(Request $request)
    {
        return self::create(["season_name" => $request->season, "created_by" => auth()->id()]);
    }

    public static function allSeasons()
    {
        DB::table("seasons as s")->
        join("season_schedules as ss", "ss.season_id", "=", "s.id")
            ->join("teams as t", "t.id", "=", "ss.team_id")
            ->select("seasons.*", "users.name as created_by")->get();
    }

}
