<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;
use DB;

class SeasonTeams extends Model
{
    use HasFactory;

    protected $table = 'season_teams';
    protected $fillable = ['season_id', 'team_id'];

    protected static function boot()
    {
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public static function seasonteamplayers($season_id)
    {
        return DB::select("select st.season_id,st.team_id,p.id from season_teams st  join teams t
        on st.team_id=t.id  join players p on p.team_id=t.id where st.season_id=?", [$season_id]);
    }
}
