<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Ramsey\Uuid\Uuid;
use DB;

class Team extends Model
{
    use HasFactory;

    protected $fillable = [
        'uuid',
        'team_name',
        'team_logo',
        'coach_name'];

    public static function players()
    {
        return DB::table("teams")->join('players', 'players.team_id', '=', 'teams.id')
            ->select('players.*')->get();
    }

    protected static function boot()
    {
        self::creating(function ($model) {
            $model->uuid = Uuid::uuid4();
        });
        parent::boot(); // TODO: Change the autogenerated stub
    }

    public function player()
    {
        return $this->hasMany(Player::class, "team_id");
    }


}
